// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
)

const createJobOffer = `-- name: CreateJobOffer :one
INSERT INTO job_offers (
    id, title, company, location, salary, description, url, source, published_at, skills
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at
`

type CreateJobOfferParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Company     sql.NullString `json:"company"`
	Location    sql.NullString `json:"location"`
	Salary      sql.NullString `json:"salary"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Source      string         `json:"source"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Skills      sql.NullString `json:"skills"`
}

func (q *Queries) CreateJobOffer(ctx context.Context, arg CreateJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, createJobOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Salary,
		arg.Description,
		arg.Url,
		arg.Source,
		arg.PublishedAt,
		arg.Skills,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteJobOffer = `-- name: DeleteJobOffer :exec
DELETE FROM job_offers WHERE id = ?
`

func (q *Queries) DeleteJobOffer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJobOffer, id)
	return err
}

const getJobOffer = `-- name: GetJobOffer :one
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers WHERE id = ?
`

func (q *Queries) GetJobOffer(ctx context.Context, id string) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, getJobOffer, id)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getJobOfferByURL = `-- name: GetJobOfferByURL :one
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers WHERE url = ?
`

func (q *Queries) GetJobOfferByURL(ctx context.Context, url string) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, getJobOfferByURL, url)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listJobOffers = `-- name: ListJobOffers :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
ORDER BY created_at DESC 
LIMIT ? OFFSET ?
`

type ListJobOffersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobOffers(ctx context.Context, arg ListJobOffersParams) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersByCompany = `-- name: ListJobOffersByCompany :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
WHERE company = ?
ORDER BY published_at DESC
`

func (q *Queries) ListJobOffersByCompany(ctx context.Context, company sql.NullString) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersByLocation = `-- name: ListJobOffersByLocation :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
WHERE location LIKE ?
ORDER BY published_at DESC
`

func (q *Queries) ListJobOffersByLocation(ctx context.Context, location sql.NullString) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersByLocation, location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOffersBySource = `-- name: ListJobOffersBySource :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
WHERE source = ?
ORDER BY published_at DESC 
LIMIT ? OFFSET ?
`

type ListJobOffersBySourceParams struct {
	Source string `json:"source"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListJobOffersBySource(ctx context.Context, arg ListJobOffersBySourceParams) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listJobOffersBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobOffers = `-- name: ListRecentJobOffers :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
ORDER BY published_at DESC 
LIMIT ?
`

func (q *Queries) ListRecentJobOffers(ctx context.Context, limit int64) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobOffers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobOffers = `-- name: SearchJobOffers :many
SELECT id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at FROM job_offers 
WHERE 
    title LIKE ? OR 
    company LIKE ? OR 
    description LIKE ? OR
    skills LIKE ? OR
    location LIKE ? OR
    salary LIKE ?

ORDER BY published_at DESC
LIMIT ? OFFSET ?
`

type SearchJobOffersParams struct {
	Title       string         `json:"title"`
	Company     sql.NullString `json:"company"`
	Description sql.NullString `json:"description"`
	Skills      sql.NullString `json:"skills"`
	Location    sql.NullString `json:"location"`
	Salary      sql.NullString `json:"salary"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

func (q *Queries) SearchJobOffers(ctx context.Context, arg SearchJobOffersParams) ([]JobOffer, error) {
	rows, err := q.db.QueryContext(ctx, searchJobOffers,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.Skills,
		arg.Location,
		arg.Salary,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobOffer{}
	for rows.Next() {
		var i JobOffer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Url,
			&i.Source,
			&i.PublishedAt,
			&i.Skills,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobOffer = `-- name: UpdateJobOffer :one
UPDATE job_offers 
SET 
    title = ?,
    company = ?,
    location = ?,
    salary = ?,
    description = ?,
    published_at = ?,
    skills = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at
`

type UpdateJobOfferParams struct {
	Title       string         `json:"title"`
	Company     sql.NullString `json:"company"`
	Location    sql.NullString `json:"location"`
	Salary      sql.NullString `json:"salary"`
	Description sql.NullString `json:"description"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Skills      sql.NullString `json:"skills"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateJobOffer(ctx context.Context, arg UpdateJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, updateJobOffer,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Salary,
		arg.Description,
		arg.PublishedAt,
		arg.Skills,
		arg.ID,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertJobOffer = `-- name: UpsertJobOffer :one
INSERT INTO job_offers (
    id, title, company, location, salary, description, url, source, published_at, skills
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(url) DO UPDATE SET
    title = excluded.title,
    company = excluded.company,
    location = excluded.location,
    salary = excluded.salary,
    description = excluded.description,
    published_at = excluded.published_at,
    skills = excluded.skills,
    last_seen_at = CURRENT_TIMESTAMP
RETURNING id, title, company, location, salary, description, url, source, published_at, skills, created_at, last_seen_at
`

type UpsertJobOfferParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Company     sql.NullString `json:"company"`
	Location    sql.NullString `json:"location"`
	Salary      sql.NullString `json:"salary"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Source      string         `json:"source"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Skills      sql.NullString `json:"skills"`
}

func (q *Queries) UpsertJobOffer(ctx context.Context, arg UpsertJobOfferParams) (JobOffer, error) {
	row := q.db.QueryRowContext(ctx, upsertJobOffer,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Salary,
		arg.Description,
		arg.Url,
		arg.Source,
		arg.PublishedAt,
		arg.Skills,
	)
	var i JobOffer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Url,
		&i.Source,
		&i.PublishedAt,
		&i.Skills,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
