// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type JobOffer struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Company     sql.NullString `json:"company"`
	Location    sql.NullString `json:"location"`
	Salary      sql.NullString `json:"salary"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Source      string         `json:"source"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Skills      sql.NullString `json:"skills"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	LastSeenAt  sql.NullTime   `json:"last_seen_at"`
}
