// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateJobOffer(ctx context.Context, arg CreateJobOfferParams) (JobOffer, error)
	DeleteJobOffer(ctx context.Context, id string) error
	GetJobOffer(ctx context.Context, id string) (JobOffer, error)
	GetJobOfferByURL(ctx context.Context, url string) (JobOffer, error)
	ListJobOffers(ctx context.Context, arg ListJobOffersParams) ([]JobOffer, error)
	ListJobOffersByCompany(ctx context.Context, company sql.NullString) ([]JobOffer, error)
	ListJobOffersByLocation(ctx context.Context, location sql.NullString) ([]JobOffer, error)
	ListJobOffersBySource(ctx context.Context, arg ListJobOffersBySourceParams) ([]JobOffer, error)
	ListRecentJobOffers(ctx context.Context, limit int64) ([]JobOffer, error)
	SearchJobOffers(ctx context.Context, arg SearchJobOffersParams) ([]JobOffer, error)
	UpdateJobOffer(ctx context.Context, arg UpdateJobOfferParams) (JobOffer, error)
	UpsertJobOffer(ctx context.Context, arg UpsertJobOfferParams) (JobOffer, error)
}

var _ Querier = (*Queries)(nil)
